### ISSUE TITLE
As a user, I want to see the latest AQ measurements of any city, so I can stay up to date

### ISSUE THREAD

**Issue by miguelperezcolom** [miguelperezcolom/openaq#1]
## Description

The user needs to be able to select a city of Spain and, after clicking a buton, see the latest results from OpenAQ for that city

## Acceptance criteria

- [x]  The user can select the city
- [x] The user can trigger the query
- [x] the user sees the latest measurements for that city

## Tasks

- [x] create UI
- [x] create API
- [x] dockerize and document

**Comment by miguelperezcolom** [comment]
client side only version is ready at https://glistening-bublanina-53138f.netlify.app/

**Comment by miguelperezcolom** [comment]
logic has been published as as azure functions.

urls are:

https://miguelperezcolom-openaq.azurewebsites.net/api/GetCitiesFunction
https://miguelperezcolom-openaq.azurewebsites.net/api/GetMeasurementsFunction?city=Madrid
